title = 'Caio Barros'
theme = "PaperMod"
languageCode = "en-us"
[params]
	dateFormat = '2006-01-02'
	icon = '/favicon.ico'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[menu]
  [[menu.main]]
    name = "Posts in English"
    url = "/langs/en"
    weight = 1
  [[menu.main]]
    name = "Postagens em Português"
    url = "/langs/pt-br"
    weight = 2
[taxonomies]
  tag = "tags"
  lang = "langs"
